### ISSUE TITLE
jdlbotserver.exe won't start because of special characters in Username

### ISSUE THREAD

**Issue by GrueneNeun** [thawn/jdlbot#10]
I have a special Character in my Windows Username ("ü") and it is not properly escaped by jdlbot and it won't start. is it possible to get around this behaviour (changing the default config path to active directory for example) or insert proper escaping ?

![error](https://user-images.githubusercontent.com/12693822/29210222-c1c9d7c0-7e92-11e7-86fc-aa0485618197.jpg)

**Comment by thawn** [comment]
Could you please give me the error message you get when you start 
jdlbot.exe from the command line?

**Comment by GrueneNeun** [comment]
Sorry, i don't have a jdlbot.exe - i just downloaded the binary from this repository - did i miss something ? In a virtual machine jdlbotserver.exe worked fine...

**Comment by thawn** [comment]
sorry, i meant jdlbotserver.exe

**Comment by GrueneNeun** [comment]
The Error message is the one in the attached Picture:
"DBI connect('dbname=C:\Users\Gr³neNeun\AppData\Roaming\jdlbot\config.sqlite','',...) failed: unable to open database file at script/jdlbotServer.pl line 95.
Could not open config file."
My Username is "GrüneNeun" and i think this is the problem because the "ü" is not escaped properly...

**Comment by thawn** [comment]
I'll look into it but at the moment I am very pressed for time so please 
don't expect anything soon.
The problem is not simply adding quotes to a variable because it is not 
about special character escaping but about how unicode characters are 
handled in windows and perl and it is not trivial to find a portable 
solution. Also, I will need to set up a special virtual machine with 
german language settings for testing.

**Comment by GrueneNeun** [comment]
No Problem, i didn't even hope to hear from you that soon ;)
If i can help in testing or something pls let me know. Would it be possible to change the Path where the Database and config is stored by a command line switch ? So that jdlbotserver uses the directory it is started from instead of the profile path ? This would help too, or at least get around my problem...

**Comment by thawn** [comment]
you could actually try to start jdlbotserver.exe with the -c option:
  jdlbotserver.exe -c "C:\Path\to\jdlbot\"

however, I have not tested that option in a long time so I am not sure 
it will work.

**Comment by GrueneNeun** [comment]
Tested it and the error remains the same...

**Comment by thawn** [comment]
o.k. then there won't be an easy fix.

Meanwhile, have a look at flexget. I myself switched to that. It 
basically does the same as jdlbot but is much more flexible (but also 
more difficult to configure).

Cheers

**Comment by thawn** [comment]
unfortunately, jdlbot [is not maintained any more](https://github.com/thawn/jdlbot#not-maintained-any-longer). I suspect that even if you managed to solve this particular problem, the web scrapers will all be out of date. I recommend using flexget instead.
