### ISSUE TITLE
macOS: Does not work under High Sierra

### ISSUE THREAD

**Issue by badrabbit** [thawn/jdlbot#11]
jDlBot won't open under macOS High Sierra 10.13.3:

![bildschirmfoto 2018-04-14 um 15 35 43](https://user-images.githubusercontent.com/78358/38768852-05ff56d0-3ffa-11e8-832e-7b0ac0b611eb.png)

"jDlBot" isn't optimized for your Mac.
The app must be updated from the developer...

![bildschirmfoto 2018-04-14 um 15 42 59](https://user-images.githubusercontent.com/78358/38768889-96607d8a-3ffa-11e8-89d1-8d3d40bbf861.png)

**Comment by badrabbit** [comment]
MacBook-12:~ hubsi$ /Applications/jDlBot.app/Contents/Resources/jdlbotServer 
Can't load '/var/folders/8w/fg8x5rnn71l_c1fvdqtq58700000gn/T/par-6875627369/cache-3936754597b33fd77f2149842412f3376ce0ef77/beb061a7.bundle' for module Net::SSLeay: dlopen(/var/folders/8w/fg8x5rnn71l_c1fvdqtq58700000gn/T/par-6875627369/cache-3936754597b33fd77f2149842412f3376ce0ef77/beb061a7.bundle, 1): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /var/folders/8w/fg8x5rnn71l_c1fvdqtq58700000gn/T//par-6875627369/cache-3936754597b33fd77f2149842412f3376ce0ef77/beb061a7.bundle
  Reason: image not found at /System/Library/Perl/5.18/darwin-thread-multi-2level/DynaLoader.pm line 194.
 at /Library/Perl/5.18/PAR/Heavy.pm line 78.
Compilation failed in require at script/jdlbotServer.pl line 9.
BEGIN failed--compilation aborted at script/jdlbotServer.pl line 9.

**Comment by thawn** [comment]
unfortunately, jdlbot [is not maintained any more](https://github.com/thawn/jdlbot#not-maintained-any-longer). I suspect that even if you managed to solve this particular problem, the web scrapers will all be out of date. I recommend using flexget instead.
