### ISSUE TITLE
Clear history when new filter/host is added?

### ISSUE THREAD

**Issue by kepi** [thawn/jdlbot#13]
I'm not sure if I'm right but it seems that when I add new feed, it got parsed and stored into history. Then I add new filter but it is not matched against already parsed feed items.

Maybe clearing history is easiest approach?

**Comment by thawn** [comment]
unfortunately, jdlbot [is not maintained any more](https://github.com/thawn/jdlbot#not-maintained-any-longer). I suspect that even if you managed to solve this particular problem, the web scrapers will all be out of date. I recommend using flexget instead.
