### ISSUE TITLE
jdlbotserver won't install because of SQLite error

### ISSUE THREAD

**Issue by ChocGoddess** [thawn/jdlbot#14]
![image](https://user-images.githubusercontent.com/61786906/75879893-3750e400-5dea-11ea-9e8a-75bb4577896a.png)
DBD::SQLite::db selectall_arrayref failed: no such table: config at script/jdlbotServer.pl line 122.
Can't fetch configuration

I am running Win 10 and downloaded jdlbotServer 0.5.1 but keep getting the above error.  What can I do to fix this?

**Comment by thawn** [comment]
unfortunately, jdlbot [is not maintained any more](https://github.com/thawn/jdlbot#not-maintained-any-longer). I suspect that even if you managed to get it to work, the web scrapers will all be out of date. I recommend using flexget instead.
