### ISSUE TITLE
Feature Request: feedburner support

### ISSUE THREAD

**Issue by TehMaster** [thawn/jdlbot#5]
Please implement support for feeds from feedburner.com

**Comment by thawn** [comment]
Any Atom or RSS feed should work. In what way are the feeds from feedburner.com not working for you?

**Comment by TehMaster** [comment]
I receive an error when trying to load feeds from feedburner.
Link: http://feeds.feedburner.com/rlsbb/MrCi
![image](https://cloud.githubusercontent.com/assets/381695/22405761/94c631ee-e5fc-11e6-848a-cbc4bd9f98c9.png)

**Comment by thawn** [comment]
that's weird, another feed from feedburner works for me.
Maybe that specific feed has some errors.

**Comment by TehMaster** [comment]
Weird. Must be the feed. I appreciate you looking into this Thawn. Loving jdlbot. Thanks!

**Comment by thawn** [comment]
Just an additional info for you: I'm using the perl module XML::FeedPP for parsing the feeds. Apparently that module cannot handle this particular feed.
