### ISSUE TITLE
Filters on links (not just titles)

### ISSUE THREAD

**Issue by TehMaster** [thawn/jdlbot#6]
I am noticing a trend for TV shows that i think an additional feature could help with. Many sites combine their posts for HDTV and 720P versions of a show (instead of two different posts). I believe this behavior is making it difficult for jdlbot to parse the correct link from the RSS feed. JDLbot matches the show title using the correct 720P filter, but then grabs the HDTV download link since it appears higher in the rss feed.

Could a feature be added to also check the links for matching criteria (like showTitle.720) and not just the show title? I think this would ensure jdlbot grabs the correct links for these types of combined posts.

**Comment by thawn** [comment]
The links are filtered already. However, that filter (Link Types) is only intended to filter for the hostnames, it cannot currently filter other parts of the links.

The problem is that for most filehosters, the links are cryptic and do not contain the filenames or any other useful parseable stuff.

Could you please send me a link to an example so that I have a testcase?

**Comment by TehMaster** [comment]
Hey Thawn,

I figured this was the case (with how the link filters work). I think my
case may be a bit feed specific, but maybe there are others who have the
same issue. I foun d a sample post to highlight my experience. Notice how
the post has combined HDTV and 720P links, and the HDTV links always come
first which is what jdlbot grabs in most cases.


Website Post - http://2ddl.org/house-husbands-s05e03-hdtv-x264-w4f/
Feed XML of same post - http://pastebin.com/JKJRDa3G

Hope this helps! Thanks!!!

**Comment by thawn** [comment]
o.k. I see the problem.

In principle, it should be possible to fix this for your particular case by changing line **189** in **Feed.pm**:
From:
				`my ($linkType) = ( $link =~ /^https?:\/\/([^\/]+)\// );`
to
				`my $linkType = $link;`

and then put a regular expression that fits your needs in the "Link Types:" field.

I am hesitant to change this for everyone, for two reasons:
1) It makes the link filtering more complicated for the users
2) I don't have time to properly test this at the moment

Therefore, I would ask you to clone (or fork) your own copy of the source code and make the change yourself (download and install git bash to do so).

It is possible to run the source code directly under windows if you install strawberry perl and then install the required perl modules by executing the following command (all on one line) on the command line: 
 `cpan -f -i EV AnyEvent::HTTP AnyEvent::HTTPD Error Path::Class File::Path Text::Template XML::FeedPP Web::Scraper JSON::XS Getopt::Long Perl::Version DBIx::MultiStatementDo List::MoreUtils Log::Message::Simple URI::Find LWP::Protocol::https Net::SSLeay` 

good luck.

**Comment by thawn** [comment]
I just changed the link filtering to work on the entire url, not only the hostname in version 0.5.1. That way, you should be able to do what you want.

Cheers

**Comment by TehMaster** [comment]
Hey Thawn,

That is great to hear and very much appreciated. I had tried to compile my own version back when we initially discussed this without success. With the new method can you give me an example on how i would use the file size filter? Regex is not my specialty.. :(

Given the below details from the feed how would i use regex to specify to search for 300MB or above (which would then grab the link below for the 926 MB file)?

<p style="text-align: center;"><strong>Conan.2017.04.20.Dana.Carvey.720p.HDTV.x264-CROOKS</strong><br />
MKV | AC3 CBR | 926MB<br />
NFO – <a href="http://extratorrent.cc/search/?search=Conan.2017.04.20.Dana.Carvey.720p.HDTV.x264-CROOKS">Torrent Search</a> – <a href="http://nitroflare.com/view/E9725D8DA671763/conan.2017.04.20.dana.carvey.720p.hdtv.x264-crooks.mkv">NiTROFLARE</a> – <a 

Thanks,
Zach

**Comment by thawn** [comment]
Hi Zach,

could you please post the whole item element starting from <item> until 
</item>.

Unfortunately, so far the file size filter only works if the file size 
appears in the title. I'll try to expand that to anywhere in the feed 
item eventually but have not had the time to do so yet.

Best regards,

Thawn

**Comment by TehMaster** [comment]
Hi Thawn,

I misunderstood what the file size was checking and thought it was looking through the feed and not just the title. Hopefully the new filter on links will help grab only the 720 or 1080 versions, but the file size check would be an extra layer to ensure nothing non-HD gets picked up.

I don’t have the same code, but here is another example from the same feed:

<item>
		<title>Judge Rinders Crime Stories S02E06 720p HDTV x264-QPEL</title>
		<link>http://rlsbb.ru/judge-rinders-crime-stories-s02e06-720p-hdtv-x264-qpel/</link>
		<comments>http://rlsbb.ru/judge-rinders-crime-stories-s02e06-720p-hdtv-x264-qpel/#comments</comments>
		<pubDate>Sat, 22 Apr 2017 13:16:43 +0000</pubDate>
		<dc:creator><![CDATA[Lisa]]></dc:creator>
				<category><![CDATA[TV Shows]]></category>

		<guid isPermaLink="false">http://rlsbb.ru/?p=107694</guid>
		<description><![CDATA[In December 2014, businessman Andreas Christopheros was working from home while his wife Pia and their 18-month-old son slept in the next room. As Andreas answered a knock at the door, a man threw a beaker full of sulphuric acid directly into Andreas&#8217; face, before disappearing. While doctors battled to save Andreas&#8217; life, it was [&#8230;]]]></description>
				<content:encoded><![CDATA[<p><img class="aligncenter" src="http://img.rlsbb.RU/images/MiN0qQCXg.jpg" alt="" /></p>
<p>In December 2014, businessman Andreas Christopheros was working from home while his wife Pia and their 18-month-old son slept in the next room. As Andreas answered a knock at the door, a man threw a beaker full of sulphuric acid directly into Andreas&#8217; face, before disappearing. While doctors battled to save Andreas&#8217; life, it was down to the Devon &amp; Cornwall police to catch the man who was responsible and find out why.</p>
<p><strong>Links:</strong> <a href="https://itvstudios.com/programmes/judge-rinder-s-crime-stories">HOMEPAGE</a> – <a href="http://thetvdb.com/?tab=series&amp;id=313178&amp;lid=7">TVDB</a></p>
<p style="text-align: center;"><strong>Judge.Rinders.Crime.Stories.S02E06.720p.HDTV.x264-QPEL</strong><br />
MKV | AC3 CBR | 254MB<br />
NFO – <a href="http://extratorrent.cc/search/?search=Judge.Rinders.Crime.Stories.S02E06.720p.HDTV.x264-QPEL">Torrent Search</a> – <a href="http://nitroflare.com/view/DCD1738BDE7FCAD/Judge.Rinders.Crime.Stories.S02E06.720p.HDTV.x264-QPEL.mkv">NiTROFLARE</a> – <a href="http://uploaded.net/file/rqqafnqy/Judge.Rinders.Crime.Stories.S02E06.720p.HDTV.x264-QPEL.mkv">UPLOADED</a> – <a href="http://rapidgator.net/file/77f9637b3f659c1b90421d6279eab146/Judge.Rinders.Crime.Stories.S02E06.720p.HDTV.x264-QPEL.mkv.html">RAPiDGATOR</a> – <a href="http://uploadrocket.net/59vh4wfstxqi/Judge.Rinders.Crime.Stories.S02E06.720p.HDTV.x264-QPEL.mkv.html">UploadRocket</a></p>
<p style="text-align: center;"><strong>Judge.Rinders.Crime.Stories.S02E06.HDTV.x264-RBB <span style="color: #ff0000;">[P2P]</span></strong><br />
MP4 | AAC VBR | 91MB<br />
NFO – <a href="http://extratorrent.cc/search/?search=Judge.Rinders.Crime.Stories.S02E06.HDTV.x264-RBB">Torrent Search</a> – <a href="http://nitroflare.com/view/6458DCAD11D7313/Judge.Rinders.Crime.Stories.S02E06.480p.x264-rbb.mp4">NiTROFLARE</a> – <a href="http://uploaded.net/file/2ohw8a11/Judge.Rinders.Crime.Stories.S02E06.480p.x264-rbb.mp4">UPLOADED</a> – <a href="http://rapidgator.net/file/fa65ba9f7c69c79783fd9e626f9a62ce/Judge.Rinders.Crime.Stories.S02E06.480p.x264-rbb.mp4.html">RAPiDGATOR</a> – <a href="http://uploadrocket.net/d0rp6oair1ak/Judge.Rinders.Crime.Stories.S02E06.480p.x264-rbb.mp4.html">UploadRocket</a></p>
]]></content:encoded>
			<wfw:commentRss>http://rlsbb.ru/judge-rinders-crime-stories-s02e06-720p-hdtv-x264-qpel/feed/</wfw:commentRss>
		<slash:comments>15</slash:comments>
<enclosure url="http://nitroflare.com/view/DCD1738BDE7FCAD/Judge.Rinders.Crime.Stories.S02E06.720p.HDTV.x264-QPEL.mkv" length="0" type="video/x-matroska" />
<enclosure url="http://uploaded.net/file/rqqafnqy/Judge.Rinders.Crime.Stories.S02E06.720p.HDTV.x264-QPEL.mkv" length="0" type="video/x-matroska" />
<enclosure url="http://nitroflare.com/view/6458DCAD11D7313/Judge.Rinders.Crime.Stories.S02E06.480p.x264-rbb.mp4" length="0" type="video/mp4" />
<enclosure url="http://uploaded.net/file/2ohw8a11/Judge.Rinders.Crime.Stories.S02E06.480p.x264-rbb.mp4" length="0" type="video/mp4" />
		</item>

**Comment by thawn** [comment]
Hi Zach,

unfortunately, file size filtering will not work here. In general, this 
will be very difficult to implement for rlsbb, because the posted links 
often don't match the title in terms of file size or resolution. I think 
the link filter is the right choice in this case because it will allow 
you a final check for the resolution for example with a regex like this: 
.*(720p|1080p).* which checks whether 720p or 1080p appear somewhere in 
the link url.

Good luck, and let me know if you have further questions.

Cheers

Thawn
