### ISSUE TITLE
Feature request: add youtube channel download support

### ISSUE THREAD

**Issue by ghost** [thawn/jdlbot#7]
Hello,

Would like to use jdlbot to automatically download Youtube videos from some channels.

Unfortunately, the same links are always sent to Jdownloader.
How can I prevent this?
So that each video (download) is sent only once to jdownloader?

**Comment by thawn** [comment]
There is a checkbox in the filter configuration called "disable when 
found" if you enable that, then jdlbot will disable the filter as soon 
as it finds the movie.

for tv series, each episode is downloaded only once, provided the 
episodes appear in the Format S01E01 or as a date.

**Comment by cpzruk123** [comment]
Ok, then it is unfortunately not possible.
Since the Youtube videos do not have a numming or date in the title.

**Comment by thawn** [comment]
Feature: "enabled download of youtube channel as tv series" was added in commit 7bf1f58.

You can now add a youtube channel rss feed (https://www.youtube.com/feeds/videos.xml?channel_id=<channel_id>)
enter .* as filter
add youtube.com to the link types
It will check the published date and only download videos that have been published on a newer date than the last downloaded video.
